apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebe-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodebe-nodejs
  template:
    metadata:
      labels:
        app: nodebe-nodejs
    spec:
      containers:
      - name: nodebe-nodejsp
        image: cvsmdudxpdemo.azurecr.io/nodebe-nodejs:{deploy_version}  # Updated ACR image path
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"

---
apiVersion: v1
kind: Service
metadata:
  name: nodebe-nodejs
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nodebe-nodejs
