apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-v1
spec:
  selector:
    app: my-nodejs-v1  # Fixed selector (matching deployment)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Matches the containerPort in deployment
  type: LoadBalancer

