const config = require('./config');

const msg = {
  "v_typ": [{
    [config.validationType.String]: "must be a text value!",
    [config.validationType.Number]: "must be a numeric value!",
    [config.validationType.Integer]: "must be an integer value!",
    [config.validationType.Float]: "must be a float value!",
    [config.validationType.Boolean]: "must be a boolean value!",
    [config.validationType.Array]: "must be a array value!",
    [config.validationType.ArrayOfInteger]: "value must be a array of integer!",
    [config.validationType.ArrayOfObject]: "value must be a array of object!",
    [config.validationType.JSON]: "must be a JSON value!",
    [config.validationType.Email]: "is invalid!",
    [config.validationType.Password]: "is invalid!",
    [config.validationType.RegEx]: "is invalid!",
    [config.validationType.Object]: "must be a object value!",
  }],
  "v_txt": [{

    // Common Text
    skip: "Page Number",
    limit: "Record Limit",
    createdAt: "Created On",
    updatedAt: "Updated On",
    ID: "ID",
    isTrashed: "IsTrashed",
    filterData: "Filter data",
    data: "Data",
    pageNumber: "Page number",

    // Project Text
    loginID: "Login ID",
    formID: "Form ID",
    userID: "User ID",
    emailID: "Email ID",
    mobileNO: "Mobile NO",
    transactionID: "Transaction ID",
    formData: "Form Data",
    filterString: "Filter string",
    languageCode: "Language Code",
    status: "Status",
    AssignmentType: "Assignment Type",
    payloadResourceID: "Payload resource ID",
    assigner: "Assigner",
    assignee: "Assignee",
    assignerNotes: "Assigner Notes",
    notificationTypeID: "Notification Type ID",
    payload: "Payload",
    notificationStatus: "Notification Status",
    loginType: "Login Type",
    OTP: 'OTP',
    assignmentID: 'Assignment ID',
    score: 'Score',
    sessionID: 'Session ID',
    type: 'Type',
    completeByTime: 'Complete By Time',
    assignerID: 'Assigner ID',
    assigneeID: 'Assignee ID',
    notificationID: "Notification ID",
    beforeID: "Before ID",
    countryCode: "Country Code",
    resourceID: "Resource ID",
    tag: "Tag",
    effectiveFrom: "Effective from",
    groupDescription: 'Group Description',
    groupName: 'Group Name',
    ownerID: 'Owner ID',
    WGID: "Workgroup ID",
    memberIDs: "Member IDs",
    memberID: "Member ID",
    title: "Title",
    content: "Content",
    description: "Description",
    resourceType: "Resource Type",
    resourceTypeID: "Resourcetype ID",
    stats: "Stats",
    lastUpdateBy: "Last update by",
    settings: "Settings",
    taskGroup: "Task Group",
    reassignReference: "Reassign reference",
    completeBy: "Complete By",
    expiryDT: "Expiry date",
    isBlocking: "IsBlocking",
    iniMessage: "Ini message",
    expWarningMessage: "Expiry warning message",
    expMessage: "Expiry message",
    taskID: "Task ID",
    fromUserID: "From user ID",
    toUserID: "To user ID",
    toUserIDARRAY: "To UserID's",
    Notes: "Notes",
    URL: "URL",
    searchKey: "Search Key",
    searchString: "Search string",
    termID: "Term ID",
    term: "Term",
    attributes: "Attributes",
    termSetID: "Termset ID",
    termSetName: "Termset name",
    destinationTermID: "Destination term ID",
    mergingTerms: "Merging terms",
    requestID: "Request ID",
    seriesID: "Series ID",
    evalNotes: "Evaluate notes",
    eventRef: "Event Reference",
    visibility: "Visibility",
    assigneeNotes: "Assignee Notes",
    infoFields: "Info fields",
    resourceFormat: "Resource format",
    resource: "resource",
    skills: "skills",
    index: "Index",
    workgroup: "Workgroup",
    authors: "Authors",
    department: "Department",
    parentTermID: "Parent term ID",
    role: "Role",
    roleID: "Role ID",
    competencyID: "Competency ID",
    skill: "Skill",
    skillLevel: "Skill level",
    deleteSkill: "Delete skill",
    parentMessageID: "Parent Message ID",
    messageID: "Message ID",
    message: "Message",
    lastupdatedBy: "lastupdatedBy",
    resourceList: "Resource list",
    resourceCount: "Resource count",
    peopleCount: "People count",
    createdBy: "Created By",
    count: "Count",
    playlistID: "Playlist ID",
    name: "Name",
    update: "Update",
    updateProfile: "Update profile",
    domainID: "Domain ID",
    id: "ID",
    Name: "Name",
    link: "Link",
    thumbnail: "Thumbnail",
    innerHtml: "innerHTML",
    reportType: "Report type",
    forRole: "For role",
    interests: "Interests",
    references: "References",
    functionRole: "FunctionRole",
    company: "Company",
    location: "Location",
    city: "City",
    country: "Country",
    designation: "Designation",
    dateOfJoining: "Date of Joining",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    firstName: "First Name",
    lastName: "Last Name",
    duration: "Duration",
    bookmark: "Bookmark",
    key: "Key",
    caption: "Caption",
    timeline: "Timeline",
    indice: "Indice",
    lanCode: "Language Code",
    skillID: "Skill ID",
    endorse: "Endorse",
    rating: "Rating",
    category: "Category",
    includeCurrentUser: "Include Current User",
    global: "Global",
    interestID: "Interests ID",
    reporteeUserID: "Reportee user ID",
    reportingToUserID: "Reporting user ID",
    object: "Object",
    objectID: "Object ID",
    userType: "User type",
    course: "Course",
    courseDurationInHrs: "Course duration in hours",
    minScoreForCertification: "Minimum score for certification",
    enforcePrerequisites: "Enforce Prerequisites",
    prerequisiteSkills: "Prerequisite Skills",
    courseModules: "Course Modules",
    moduleName: "Module Name",
    activites: "Activites",
    courseID: "Course ID",
    activityType: "Activity Type",
    typeName: "Type Name",
    actorUserID: "Actor User ID",
    eventID: "Event ID",
    trigger: "Trigger",
    device: "Device",
    condition: "Condition",
    IP: "IP Address",
    actorName: "Actor Name",
    resourceTypeName: "Resource Type Name",
    external: "External",
    format: "Format",
    keywords: "Keywords",
    timeStamp: "TimeStamp",
    remarks: "Remarks",
    feedbackerID: "Feedbacker ID",
    currentUserID: "Current user ID",
    eventType: "Event type",
    experienceAtJoining: "Experience At Joining",
    desiredEngPt: "Desired engagement point",
    desiredLearningPt: "Desired learning point",
    learningPoints: "Learning points",
    engagementPoints: "Engagement points",
    tenureID: "Tenure ID",
    questionType: "Question type",
    question: "Question",
    details: "Details",
    options: "Options",
    option: "Option",
    rightOption: "Right option",
    moderate: "Moderate",
    termSetType: "Term set type",
    autogenerateQuestion: "Autogenerate question",
    testID: "Test ID",
    marks: "Marks",
    noOfQuestion: "Number of questions",
    questions: "Questions",
    userTestID: "User test ID",
    questionID: "Question ID",
    markForReview: "Mark For Review",
    answer: "Answer",
    assessmentID: "Assessment ID",
    departmentID: "Department ID",
    functionalRoleID: "Functional Role ID",
    countryID: "Country ID",
    locationID: "Location ID",
    genderID: "Gender ID",
    enrolUserID: "Enrol user ID",
    parentRoleID: "Parent role ID",
    segments: "Segments",
    competencies: "Competencies",
    linkedResource: "Linked resource",
    functionalRole: "Functional Role",
    timeSpent: "Time spent",
    includeWorkGroup: "Include Workgroup",
    endUserID: "End UserID",
    assessedUserID: "Assessed UserID",
    versionNumber: "Version number",
    source: "Source",
    certificateFile: "Certificate File",
    issuingAuthority: "Issuing Authority",
    includeModeration: "Include Moderation",
    issuingAuthorityID: "issuing Authority ID",
    issuingAuthorityName: "issuing Authority Name",
    submittedTo: "Submitted To",
    pageToken: "Page Token",
    notificationType: "Notication type",
    totalTime: "totalTime",
    fromTimeStamp: "From timestamp",
    toTimeStamp: "To timestamp",
    ageGroup: "Age group",
    tenure: "Tenure",
    stimulationFunctions: "Stimulation functions",
    moduleID: "Module ID",
    postUserID: "Post user ID",
    functionRoleID: "Function Role ID",
    cityID: "City ID",
    ageGroupID: "Agegroup ID",
    eventKey: "Event Key",
    authority: "Authority",
    date: "Date",
    resRef: "Resource reference",
    evidence: "Evidence File",
    venue: "Venue",
    meetingLink: "Meeting Link",
    registrationType: "Registration Type",
    registerBy: "Register By",
    time: "Time",
    reimbursementApproval: "Reimbursement Approval",
    registerLearningID: "Register Learning ID",
    completionDate: "Completion Date",
    enrolmentDate: "Enrolment Date",
    progressPercentage: "Progress Percentage",
    info: "Info",
    moderatorRemarks: "Moderator Remarks",
    nomineeID: "nomineeID",
    completedPercent: "Completed Percent",
    taggedUsers: "Tagged Users",
    channelName: "Channel Name",
    channelDescription: "Channel Description",
    subscriptionType: "Subscription Type",
    subscribeAutomatically: "Subscribe Automatically",
    channelID: "Channel ID",
    workGroupID: "Work Group ID",
    user: "User",
    channel: "Channel",
    reportedToUserID: "ReportedTo UserID",
    workgroupID: "Workgroup ID",
    passportToken: "Passport Token",
    parentGroupID: "Parent Permission Group ID",
    permissionGroupID: "Permission Group ID",
    experts: "Experts",
    startDate: "Start Date",
    endDate: "End Date",
    excludeResourceType: "Exclude ResourceType",
    includeSeedContent: "Include Seed Content",
    subscriptionPlan: "Subscription Plan",
    companyName: "Company Name",
    subscribedUsers: "Subscribed Users",
    // Status Text
    pending: 'Pending',
    inprogress: 'In-progress',
    completed: 'Completed',
    initiated: 'Initiated',
    incrementField: "Increment Field",

    commentID: "Comment ID",
    flaggedUserID: "Flagged UserID",
    reviewCategoryID: "Review Category ID",
    flaggedType: "Flagged Type",
    moderatorID: "Moderator ID",
    action: "Action",
    actionID: "actionID",
    userLog: "User log",
    followerID: "Follower ID",
    followeeID: "Followee ID",
    indexType: "Index Type",
    about: "About",
    S3Location: "S3 Location",
    RTMPURL: "RTMP URL",
    meetingURL: "Meeting URL",
    roomID: "Room ID",
    permissionGroup: "Permission Group",
    isBlock: "Is Block",
    dataID: "Data ID",
    weight: "Weight",
    promotionType: "Promotion Type",
    fromDate: "From Date",
    toDate: "To Date",
    promoID: 'Promotion ID',
    promoOrder: "Promotion Order",
    resourceGetType: "Resource Get type",
    publishDate: "Published Date",
    blockerID: "Blocker ID",
    blockeeID: "Blockee ID",
    searchType: "Search type",
    correctOption: "Correct Option",
    playerID: "Player ID",
    coachingFor: "Coaching For",
    jerseyNo: "Jersey No",
    nickName: "Nick name",
    height: "Height",
    playerFrom: "Player From",
    playerStyle: "Player Style",
    playerType: "Player Type",
    specialization: "Specialization",
    playerNation: "Player Nation",
    vibration: "Vibration",
    sound: "Sound",
    notification: "Notification",
    messages: "Messages",
    comments: "Comments",
    groups: "Groups",
    messageRequests: "Message Requests",
    newFollowers: "New Followers",
    tags: "Tags",
    shareNotification: "Share Notification",
    systemNotification: "System Notification",
    birthday: "Birthday",
    joined: "Joined",
    public: "Public",
    videoSettings: "Video Settings",
    problemID: "Problem ID",
    itHappen: "It Happen",
    problemDetails: "Problem Details",
    sendLog: "Send Log",
    autoPlayVideo: "Autoplay Video",
    displayName: "Display Name",
    didYouKnow: "Did You Know",
    permissionType: "Permission Type",
    loginMethod: "Login Method",
    schedule: "Schedule",
    notifyOnlyTo: "Notify Only To"


    // accountID: "Account ID",
    // salt: "User Token",
    // userName: "User Name",
    // firstName: "First Name",
    // lastName: "Last Name",
    // email: "Email",
    // emailID: 'Email ID',
    // companyName: "Company Name",
    // contactNumber: "Contact Number",
    // templateID: "Template ID",
    // status: "Status",
    // title: "Title",
    // roleTypeID: "Role type ID",
    // isBlocked: "IsBlocked",
    // password: "Password",
    // newPassword: "New Password",
    // oldPassword: "Old Password",
    // question: "Question",
    // securityQuestionID: "securityQuestion ID",
    // answer: "Answer",
    // encodedFile: "CSV file",
    // s3File: "S3 file name",
    // s3Directory: "S3 directory",
    // type: "Type",
    // key: "Key",
    // usage: "Usage",
    // location: "Location",
    // locationID: "Location ID",
    // parentID: "Parent ID",
    // serialNumber: "Serial Number",
    // controller: "Controller",
    // customerID: "Customer ID",
    // time: "Time",
    // colors: "Colors",
    // legendPosition: "Legend Position",
    // cols: "Columns",
    // rows: "Rows",
    // x: "X",
    // y: "Y",
    // timePeriod: "Time Period",
    // reportTypeID: "Report type ID",
    // reportID: "Report ID",
    // visualType: "Visual Type",
    // state: "State",
    // response: "Response",
    // ipAddress: "IP Address",
    // params: "Params",
    // moduleName: "Module Name",
    // method: "Method",
    // browser: "Browser",
    // shortName: "Short Name",
    // graphType: "Screen Type",
    // uniqueCardID: "Unique Card ID",
    // customerAdminID: "Customer admin ID",
    // organizationName: "Organization name",
    // companyType: "Company type",
    // companyLogo: "Company logo",
    // totalSeats: "Total seats",
    // launchDate: "Launch Date",
    // duration: "Duration",
    // discount: "Discount",
    // billingFrequency: "Billing Frequency",
    // portalDNSName: "Portal DNS Name",
    // expiryMonth: "Expiry month",
    // expiryYear: "Expiry year",
    // contactFirstName: "Contact first name",
    // contactLastName: "Contact last name",
    // billingCity: "Billing city",
    // billingZipcode: "Billing zipcode",
    // billingState: "Billing state",
    // billingCountry: "Billing country",
    // billingAddress: "Billing Address",
    // subscriptionPlanID: "Subscription Plan ID",
    // billingPhoneNumber: "Billing Phone Number",
    // cardType: "Card Type",
    // cardNumber: "Card Number",
    // CVVNumber: "CVV Number",
    // locationName: "Location Name",
    // controllerName: "Controller Name",
    // defaultAdmins: "Default Admins",
    // defaultLocations: "Default Locations",
    // pricing: "Pricing",
    // isBest: "IsBest",
    // isActive: "IsActive",
    // isTrial: "IsTrial",
    // isVisible: "IsVisible",
    // renewalCancellationDate: "Renewal Cancellation Date",
    // paymentToken: "Payment Token",
    // recurringFrequency: "Recurring Frequency",
    // recurringStartDate: "Recurring Start Date",
    // recurriRoOfInstallment: "Recurring Number Of Installment",

    // transactionUUID: "Transaction UUID",
    // transactionType: "Transaction Type",
    // referenceNumber: "referenceNumber",
    // consumerID: "Consumer ID",
    // recurringAmount: "Recurring Amount",

  }]
}

module.exports = msg
